export const uiText = {
  navigation: {
    solver: "FCX设置",
    previousSolver: "SBC求解器",
    legacySolver: "SBC Solver",
    autoSbc: "自动SBC",
    legacyAutoSbc: "Auto SBC",
    evolution: "球员进化",
  },
  loading: {
    success: "✓ FCX 加载成功",
  },
  settings: {
    pageTitle: "FCX设置",
    uiSection: "界面设置",
    walkoutRating: "开包动画最低总评",
    showClubStorageStats: "显示俱乐部和仓库统计",
    showPrices: "显示价格",
    priceCacheMinutes: "价格缓存时间（分钟）",
    inspectPrices: "检查价格缓存",
    diagnosticsCopied: "价格缓存调试信息已复制",
    diagnosticsCopyFailed: "复制价格缓存调试信息失败",
    showAutoSbcEntry: "显示自动SBC入口",
    clearPrices: "清除全部价格",
    pricesCleared: "所有价格数据已清除",
    sbcSection: "SBC设置",
    allSbcs: "全部SBC",
    chooseSbc: "选择SBC",
    allChallenges: "全部挑战",
    chooseChallenge: "选择挑战",
    solverParameters: "SBC求解参数",
    backendPort: "本地后端端口",
    backendPortHelp: "必须与 FCX 后端 EXE 中设置的端口一致；默认均为 8000。",
    restoreDefaults: "恢复默认设置",
    defaultsRestored: "设置已恢复默认值",
    autoSubmit: "一键自动提交",
    always: "始终",
    optimal: "仅最优方案",
    never: "从不",
    autoSubmitHelp:
      "设置SBC自动提交时机：始终提交任意方案、仅提交最优方案，或从不自动提交",
    tryAllInGroup: "自动尝试组内全部SBC",
    tryAllInGroupHelp: "开启后，将自动尝试同组中的全部SBC",
    useConcepts: "使用概念球员",
    useConceptsHelp:
      "开启后，求解时会包含已收集的概念球员；含概念球员的方案只会保存预览，不会自动提交。",
    autoOpenRewards: "自动打开奖励卡包",
    autoOpenRewardsHelp:
      "单挑战完成后处理其奖励；整组SBC仅在完整成功后处理准确匹配的整组奖励包。",
    ratingRange: "球员总评范围",
    minOverall: "最低总评",
    maxOverall: "最高总评",
    ratingRangeHelp: "限制求解时可使用的球员总评范围；缩小范围可加快求解，但可能错过最优方案",
    ignoreStorageExclusions: "优先使用仓库/重复球员",
    ignoreStorageExclusionsHelp: "仅在候选通过总评、价格和排除规则后降低其求解成本，不会绕过任何限制。",
    duplicateValue: "重复球员价值比例（%）",
    duplicateValueHelp: "设置重复球员相对市场价的估值比例；比例越低，越容易被使用",
    untradeableValue: "不可交易球员价值比例（%）",
    untradeableValueHelp: "设置不可交易球员相对市场价的估值比例；比例越低，越容易被使用",
    maxSolveTime: "最大求解时间（秒）",
    maxSolveTimeHelp: "后端搜索最优SBC方案时允许使用的最长时间",
    onlyStorage: "仅使用仓库球员",
    onlyStorageHelp: "开启后，SBC求解只会使用仓库中的球员",
    excludeOtherSolutions: "不使用其他SBC方案中的球员",
    excludeOtherSolutionsHelp: "开启后，其他待处理SBC方案中的球员不会用于当前求解",
    excludeObjective: "排除目标奖励球员",
    excludeObjectiveHelp: "开启后，通过目标获得的球员不会用于SBC求解",
    excludeTradable: "排除可交易球员",
    excludeTradableHelp: "开启后，可交易球员不会用于SBC求解",
    excludeSbc: "排除SBC奖励球员",
    excludeSbcHelp: "开启后，通过SBC获得的球员不会用于SBC求解",
    excludeExtinct: "排除绝版球员",
    excludeExtinctHelp: "开启后，转会市场中无挂牌的球员不会用于SBC求解",
    excludeLeagues: "排除联赛",
    excludeLeaguesHelp: "选择不允许用于SBC求解的球员联赛",
    excludeNations: "排除国家/地区",
    excludeNationsHelp: "选择不允许用于SBC求解的球员国家或地区",
    excludeTeams: "排除俱乐部",
    excludeTeamsHelp: "选择不允许用于SBC求解的球员俱乐部",
    excludeRarities: "排除稀有度",
    excludeRaritiesHelp: "选择不允许用于SBC求解的卡片稀有度",
    stop: "停止",
    enabled: "开",
    disabled: "关",
  },
  autoSbc: {
    pageTitle: "自动SBC",
    eyebrow: "FCX 自动化控制台",
    author: "一阵失心风",
    description: "集中管理滚卡流程、奖励卡包、SBC分类与执行。",
    syncing: "正在同步",
    synced: "数据已同步",
    refresh: "刷新",
    refreshData: "刷新SBC数据",
    refreshComplete: "SBC数据已刷新",
    refreshFailed: "SBC数据刷新失败，请稍后重试",
    syncFailed: "同步失败",
    loading: "正在载入自动SBC数据…",
    loadFailed: "自动SBC数据载入失败，请稍后重新进入此页面。",
    actionsTitle: "快速操作",
    sbcListTitle: "可用SBC",
    emptySbcs: "当前分类中没有可用的SBC。",
    packs: "卡包",
    tradable: "可交易",
    untradeable: "不可交易",
    coins: "金币",
    openAllPacks: "打开全部卡包",
    openAllDescription: "打开所有可用卡包",
    myPacks: "我的卡包",
    clickToOpen: "点击打开",
    selectSbcCategory: "选择SBC分类",
    categories: "SBC分类",
    clickToSelect: "点击选择",
    updatingCategory: "正在将SBC分类更新为",
    clickToStart: "点击开始",
    started: "SBC已启动",
    packDialogTitle: "选择要打开的卡包",
    packDialogDescription: "每包物品分配完成后才会继续打开下一包。",
    selectAll: "全选",
    packQuantity: "开启数量",
    openSelected: "打开所选",
    cancelRun: "取消任务",
    autoPick: "自动球员挑选",
    pickStrategy: "球员挑选依据",
    pickByRating: "按总评",
    pickByPrice: "按缓存价格",
    skipAnimation: "跳过开包动画",
    quickSellDuplicates: "快速出售低总评重复球员",
    quickSellWarning: "仅在明确开启后，低于阈值的重复球员才会被快速出售。",
    quickSellThreshold: "总评阈值",
    noPacks: "当前没有可用卡包。",
    packProgressIdle: "选择卡包并确认处理选项。",
    categoryDialogTitle: "选择SBC分类",
    categoryDialogDescription: "分类会保存到原有 sbcType 设置并立即刷新列表。",
    saveCategory: "保存分类",
    close: "关闭",
    sbcDialogDescription: "选择单个未完成挑战，或从头开始整组SBC。",
    challengeRequirements: "挑战要求",
    completed: "已完成",
    incomplete: "未完成",
    completedCount: "完成次数",
    startChallenge: "开始选中挑战",
    startSet: "开始整组SBC",
    selectChallengeHint: "请先选择一个未完成挑战。",
    ignoreValue: "忽略球员价值",
    ignoreValueHelp: "仅本次任务不读取或使用市场价格。",
  },
} as const;

export type UiText = typeof uiText;
